import React, { useState, useEffect, useRef, Dispatch, SetStateAction } from 'react';
import { FaClipboardList, FaCreditCard } from 'react-icons/fa';
import '../styles/payments.css';

interface PaymentDetails {
  cardNumber: string;
  expiry: string;
  cvv: string;
}

interface PaymentProps {
  paymentDetails: PaymentDetails;
  setIsComplete: Dispatch<SetStateAction<boolean>>;
  onError: (errorCode: string) => void;
  onBack: () => void;
  onNext: () => void;
  pspid: string;
  orderId: string;
  acceptUrl: string;
  exceptionUrl: string;
  preloadFlexUrl: string | null;
  amount: number;
  product: string;
  /**
   * Bespoke marketing description generated by the pitch builder.
   * Displayed in the service summary to help convince the user to
   * complete their purchase.
   */
  pitchDescription: string;
  workType: string;
}

const Payment: React.FC<PaymentProps> = ({
  paymentDetails,
  setIsComplete,
  onError,
  onBack,
  pspid,
  orderId,
  acceptUrl,
  exceptionUrl,
  preloadFlexUrl,
  amount,
  product,
  pitchDescription,
  onNext,
}) => {
  const [flexUrl, setFlexUrl] = useState<string | null>(preloadFlexUrl ?? null);
  const [error, setError] = useState<string | null>(null);
  const [iframeHeight, setIframeHeight] = useState<number>(0);
  const iframeRef = useRef<HTMLIFrameElement | null>(null);
  const [formReady, setFormReady] = useState(false);
  const [paymentDone, setPaymentDone] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const submitToIframe = () => {
    setSubmitting(true);
    iframeRef.current?.contentWindow?.postMessage({ flexMsg: 'submit' }, '*');
  };
  // min-height fallback

  /* Mark step 3 complete once *your* extra inputs are filled
     (you can remove this block if you rely solely on the gateway flow) */
  useEffect(() => {
    const complete = Object.values(paymentDetails).every(v => v.trim());
    setIsComplete(complete);
  }, [paymentDetails, setIsComplete]);

  /* Message listener – resize + submission flow */
  useEffect(() => {
    const handler = (e: MessageEvent) => {
      if (!e.data || typeof e.data !== 'object') return;
      if (e.data.flexMsg === 'size' && typeof e.data.height === 'number') {
        setIframeHeight(e.data.height);
      } else if (e.data.flexMsg === 'ready') {
        setFormReady(true);
      } else if (e.data.flexMsg === 'navigate' && typeof e.data.href === 'string') {
        if (e.data.href.startsWith(acceptUrl)) {
          setPaymentDone(true);
          setSubmitting(false);
          sessionStorage.setItem('paymentDone', 'true');
          localStorage.setItem('paymentSuccess', 'true');
        } else if (e.data.href.startsWith(exceptionUrl)) {
          setSubmitting(false);
          onError('SUBMIT_FAILED');
        }
      }
    };
    window.addEventListener('message', handler);
    return () => window.removeEventListener('message', handler);
  }, [acceptUrl, exceptionUrl, onError]);

  /* Build the FlexCheckout URL (unless it’s preloaded) */
  useEffect(() => {
    if (preloadFlexUrl) {
      setFlexUrl(preloadFlexUrl);
      return;   // don’t regenerate
    }
    if (!pspid || !orderId || !acceptUrl || !exceptionUrl) return;

    const generateShasignUrl = async () => {

      const params: Record<string, string> = {
        'ACCOUNT.PSPID':           pspid,
        'ALIAS.ORDERID':           orderId,
        'PARAMETERS.ACCEPTURL':    acceptUrl,
        'PARAMETERS.EXCEPTIONURL': exceptionUrl,
        /* Let the gateway show *all* card brands */
        'CARD.PAYMENTMETHOD':      'CreditCard',
        'LAYOUT.TEMPLATENAME':     'master.htm',
        'LAYOUT.LANGUAGE':         'en_GB',
        'ALIAS.STOREPERMANENTLY':  'Y',
      };

      try {
        const res   = await fetch('/pitch/get-shasign', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(params),
        });
        const json  = await res.json();
        if (!res.ok || !json.shasign) {
          throw new Error(`SHA-sign service returned ${res.status}`);
        }
        const query = new URLSearchParams({ ...params, SHASIGN: json.shasign }).toString();
        setFlexUrl(
          `https://mdepayments.epdq.co.uk/Tokenization/HostedPage?${query}`
        );
      } catch (err) {
        console.error(err);
        setError('Failed to load payment form. Please try again.');
        onError('FLEX_URL_FAILED');
      }
    };

    generateShasignUrl();
  }, [pspid, orderId, acceptUrl, exceptionUrl, preloadFlexUrl, onError]);

  return (
    <div className="payment-section">
      <div className="combined-section payment-pane">
        <div className="group-header">
          <FaClipboardList className="header-icon" /> Service Summary
        </div>
        <div className="service-summary-grid">
          <div className="summary-label">Product</div>
          <div className="summary-value">{product}</div>
          <div className="summary-label">Amount</div>
          <div className="summary-value">£{amount.toFixed(2)}</div>
        </div>
        <p className="pitch-description">{pitchDescription}</p>

        <div className="separator" />

        <div className="payment-details">
          <div className="group-header">
            <FaCreditCard className="header-icon" /> Payment
          </div>

        <div className="iframe-wrapper">
          {flexUrl ? (
            <iframe
              ref={iframeRef}
              title="FlexCheckout"
              src={flexUrl}
              style={{ width: '100%', height: `${iframeHeight || 300}px`, border: 0 }}
            />
          ) : (
            <div>{error ? `Error: ${error}` : 'Loading secure payment form…'}</div>
          )}
        </div>

       <div className="button-group">
         <button className="btn secondary" onClick={onBack}>
           Back
         </button>
         <button
           className="btn primary"
           onClick={submitToIframe}
           disabled={!flexUrl || !formReady || submitting || paymentDone}
         >
           Pay
         </button>
         <button className="btn primary" onClick={onNext} disabled={!paymentDone}>
           Next
         </button>
       </div>
       </div>
      </div>
    </div>
  );
};

export default Payment;
